/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jtoodle.api.test;

import java.beans.IntrospectionException;
import java.beans.PropertyEditorManager;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jtoodle.api.auth.AuthCache;
import jtoodle.api.beans.AccountInfoBean;
import jtoodle.api.beans.BeanParseUtil;
import jtoodle.api.beans.JToodlerException;
import jtoodle.api.request.GetAccountInfo;
import org.jdesktop.swingx.JXLoginPane;
import org.jdesktop.swingx.auth.LoginService;
import org.openide.nodes.BeanNode;
import org.openide.nodes.Node;
import org.openide.util.Exceptions;

/**
 *
 * @author Justo_Casablanca
 */
public class MainTestForm extends javax.swing.JFrame {

    /**
     * Creates new form MainTestForm
     */
    public MainTestForm() {
        initComponents();
		initComponents2();
    }

	private void initComponents2() {
		PropertyEditorManager.registerEditor(Date.class, DatePropertyEditor.class);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        authenticationPanel = new javax.swing.JPanel();
        userIdLabel = new javax.swing.JLabel();
        userIdTextField = new javax.swing.JTextField();
        tokenLabel = new javax.swing.JLabel();
        tokenTextField = new javax.swing.JTextField();
        apiKeyLabel = new javax.swing.JLabel();
        apiKeyTextField = new javax.swing.JTextField();
        errorCodeLabel = new javax.swing.JLabel();
        errorCodeTextField = new javax.swing.JTextField();
        errorDescLabel = new javax.swing.JLabel();
        errorDescPane = new javax.swing.JScrollPane();
        errorDescTextArea = new javax.swing.JTextArea();
        accountInfoPanel = new javax.swing.JPanel();
        accountInfoButton = new javax.swing.JButton();
        accountInfoPropertySheet = new org.openide.explorer.propertysheet.PropertySheet();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitSeparator = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userIdLabel.setLabelFor(userIdTextField);
        userIdLabel.setText("User Id:");

        userIdTextField.setEditable(false);

        tokenLabel.setLabelFor(tokenTextField);
        tokenLabel.setText("Token:");

        tokenTextField.setEditable(false);

        apiKeyLabel.setText("API Key:");

        apiKeyTextField.setEditable(false);

        errorCodeLabel.setLabelFor(errorCodeTextField);
        errorCodeLabel.setText("Error Code:");

        errorCodeTextField.setEditable(false);

        errorDescLabel.setLabelFor(errorDescPane);
        errorDescLabel.setText("<html>\nError<br>Description:\n</html>");
        errorDescLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        errorDescTextArea.setEditable(false);
        errorDescTextArea.setColumns(20);
        errorDescTextArea.setRows(5);
        errorDescPane.setViewportView(errorDescTextArea);

        javax.swing.GroupLayout authenticationPanelLayout = new javax.swing.GroupLayout(authenticationPanel);
        authenticationPanel.setLayout(authenticationPanelLayout);
        authenticationPanelLayout.setHorizontalGroup(
            authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(authenticationPanelLayout.createSequentialGroup()
                        .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(errorCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errorDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(errorDescPane, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(errorCodeTextField)))
                    .addGroup(authenticationPanelLayout.createSequentialGroup()
                        .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userIdLabel)
                            .addComponent(tokenLabel)
                            .addComponent(apiKeyLabel))
                        .addGap(37, 37, 37)
                        .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tokenTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(userIdTextField)
                            .addComponent(apiKeyTextField))))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        authenticationPanelLayout.setVerticalGroup(
            authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tokenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tokenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apiKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apiKeyLabel))
                .addGap(39, 39, 39)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorDescPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Authentication", authenticationPanel);

        accountInfoButton.setText("Account Info");
        accountInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountInfoPanelLayout = new javax.swing.GroupLayout(accountInfoPanel);
        accountInfoPanel.setLayout(accountInfoPanelLayout);
        accountInfoPanelLayout.setHorizontalGroup(
            accountInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountInfoPanelLayout.createSequentialGroup()
                        .addComponent(accountInfoButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(accountInfoPropertySheet, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                .addContainerGap())
        );
        accountInfoPanelLayout.setVerticalGroup(
            accountInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountInfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountInfoPropertySheet, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Account Info", accountInfoPanel);

        fileMenu.setText("File");

        loginMenuItem.setText("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loginMenuItem);

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(logoutMenuItem);
        fileMenu.add(exitSeparator);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void accountInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountInfoButtonActionPerformed
		String jsonString = new GetAccountInfo().request();

		try {
			AccountInfoBean bean = BeanParseUtil.toAccountInfoBean( jsonString );
			accountInfoPropertySheet.setNodes( new Node[] { new BeanNode( bean ) } );
		} catch( IntrospectionException | IOException ex ) {
			Logger.getLogger( MainTestForm.class.getName() ).log( Level.SEVERE, null, ex );
		}
    }//GEN-LAST:event_accountInfoButtonActionPerformed

    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
		JXLoginPane.Status status = JXLoginPane.showLoginDialog( this, new LoginService() {
			@Override
			public boolean authenticate( String name, char[] password, String server ) {
				errorCodeTextField.setText( null );
				errorDescTextArea.setText( null );

				try {
					AuthCache.login( name, new String( password ) );

					userIdTextField.setText( AuthCache.getUserId() );
					tokenTextField.setText( AuthCache.getToken() );
					apiKeyTextField.setText( AuthCache.getApiKey() );

					return( true );
				} catch( JToodlerException jte ) {
					errorCodeTextField.setText( "" + jte.getErrorCode() );
					errorDescTextArea.setText( jte.getMessage() );

					Logger.getLogger( MainTestForm.class.getName() ).log( Level.SEVERE, null, jte );
					return( false );
				} catch( Exception ex ) {
					errorCodeTextField.setText( ex.getClass().getName() );
					errorDescTextArea.setText( ex.getMessage() );

					Logger.getLogger( MainTestForm.class.getName() ).log( Level.SEVERE, null, ex );
					return( false );
				}
			}
		} );
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        int yn = JOptionPane.showConfirmDialog( this, "Are you sure you want to logout ?" );

		if( yn == JOptionPane.OK_OPTION ) {
			AuthCache.logout();
		}
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
		try {
			/* Create and display the form */
			java.awt.EventQueue.invokeAndWait( new Runnable() {
				@Override
				public void run() {
					new MainTestForm().setVisible(true);
				}
			});
		} catch( InterruptedException | InvocationTargetException ex ) {
			Exceptions.printStackTrace( ex );
		}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountInfoButton;
    private javax.swing.JPanel accountInfoPanel;
    private org.openide.explorer.propertysheet.PropertySheet accountInfoPropertySheet;
    private javax.swing.JLabel apiKeyLabel;
    private javax.swing.JTextField apiKeyTextField;
    private javax.swing.JPanel authenticationPanel;
    private javax.swing.JLabel errorCodeLabel;
    private javax.swing.JTextField errorCodeTextField;
    private javax.swing.JLabel errorDescLabel;
    private javax.swing.JScrollPane errorDescPane;
    private javax.swing.JTextArea errorDescTextArea;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JPopupMenu.Separator exitSeparator;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel tokenLabel;
    private javax.swing.JTextField tokenTextField;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JTextField userIdTextField;
    // End of variables declaration//GEN-END:variables
}
