/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jtoodle.api.test;

import java.awt.Component;
import java.beans.IntrospectionException;
import java.beans.PropertyEditorManager;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jtoodle.api.auth.AuthCache;
import jtoodle.api.beans.AccountInfo;
import jtoodle.api.beans.Folder;
import jtoodle.api.beans.JToodleException;
import jtoodle.api.beans.Task;
import jtoodle.api.beans.TaskQueryResult;
import jtoodle.api.request.GetAccountInfo;
import jtoodle.api.request.GetFolders;
import jtoodle.api.request.GetTasks;
import jtoodle.api.util.NullSafe;
import org.jdesktop.swingbinding.impl.ListBindingManager;
import org.jdesktop.swingx.JXLoginPane;
import org.jdesktop.swingx.auth.LoginService;
import org.openide.nodes.BeanNode;
import org.openide.nodes.Node;

/**
 *
 * @author Justo_Casablanca
 */
public class MainTestForm extends javax.swing.JFrame {

	private static final Logger logger = Logger.getLogger( MainTestForm.class.getName() );

    /**
     * Creates new form MainTestForm
     */
    public MainTestForm() {
        initComponents();
		initComponents2();
    }

	private void initComponents2() {
		PropertyEditorManager.registerEditor(Date.class, DatePropertyEditor.class);
		PropertyEditorManager.registerEditor(Class.class, ClassPropertyEditor.class);

		beanResultsComboBox.setRenderer( new DefaultListCellRenderer() {
			@Override
			public Component getListCellRendererComponent( JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus ) {
				if( value == null ) {
					setText( "<null value>" );
				} else if( value instanceof Folder ) {
					setText( ((Folder)value).getName() );
				} else if( value instanceof Task ) {
					setText( ((Task)value).getTitle() );
				} else {
					setText( value.toString() );
				}
				return this;
			}
		});

		completionComboBox.removeAllItems();
		completionComboBox.addItem( GetTasks.CompletionCriteria.All_Tasks );
		completionComboBox.addItem( GetTasks.CompletionCriteria.Completed_Tasks_Only );
		completionComboBox.addItem( GetTasks.CompletionCriteria.Uncompleted_Tasks_Only );

		tasksTable.setDefaultRenderer( Date.class, new FullDateTableCellRenderer() );
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        taskQueryResult = new jtoodle.api.test.BindableTaskQueryResult();
        tabbedPane = new javax.swing.JTabbedPane();
        authenticationPanel = new javax.swing.JPanel();
        userIdLabel = new javax.swing.JLabel();
        userIdTextField = new javax.swing.JTextField();
        tokenLabel = new javax.swing.JLabel();
        tokenTextField = new javax.swing.JTextField();
        apiKeyLabel = new javax.swing.JLabel();
        apiKeyTextField = new javax.swing.JTextField();
        errorTypeLabel = new javax.swing.JLabel();
        errorTypeTextField = new javax.swing.JTextField();
        errorCodeLabel = new javax.swing.JLabel();
        errorCodeTextField = new javax.swing.JTextField();
        errorDescLabel = new javax.swing.JLabel();
        errorDescPane = new javax.swing.JScrollPane();
        errorDescTextArea = new javax.swing.JTextArea();
        accountInfoPanel = new javax.swing.JPanel();
        accountInfoButton = new javax.swing.JButton();
        accountInfoPropertySheet = new org.openide.explorer.propertysheet.PropertySheet();
        othersPanel = new javax.swing.JPanel();
        beanTypeComboBox = new javax.swing.JComboBox();
        beanResultsComboBox = new javax.swing.JComboBox();
        beanPropertySheet = new org.openide.explorer.propertysheet.PropertySheet();
        tasksPanel = new javax.swing.JPanel();
        startDateLabel = new javax.swing.JLabel();
        startDatePicker = new org.jdesktop.swingx.JXDatePicker();
        endDateLabel = new javax.swing.JLabel();
        endDatePicker = new org.jdesktop.swingx.JXDatePicker();
        completionLabel = new javax.swing.JLabel();
        completionComboBox = new javax.swing.JComboBox();
        taskIdLabel = new javax.swing.JLabel();
        taskIdTextField = new javax.swing.JFormattedTextField();
        rowStartLabel = new javax.swing.JLabel();
        rowStartTextField = new javax.swing.JFormattedTextField();
        numRowsLabel = new javax.swing.JLabel();
        numRowsTextField = new javax.swing.JFormattedTextField();
        clearSearchutton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        searchResultsSeparator = new javax.swing.JSeparator();
        tasksInResultLabel = new javax.swing.JLabel();
        tasksInResultTextField = new javax.swing.JTextField();
        tasksInPageLabel = new javax.swing.JLabel();
        tasksInPageTextField = new javax.swing.JTextField();
        tasksScrollPane = new javax.swing.JScrollPane();
        tasksTable = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitSeparator = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userIdLabel.setLabelFor(userIdTextField);
        userIdLabel.setText("User Id:");

        userIdTextField.setEditable(false);

        tokenLabel.setLabelFor(tokenTextField);
        tokenLabel.setText("Token:");

        tokenTextField.setEditable(false);

        apiKeyLabel.setText("API Key:");

        apiKeyTextField.setEditable(false);

        errorTypeLabel.setText("Error Type:");

        errorCodeLabel.setLabelFor(errorCodeTextField);
        errorCodeLabel.setText("Error Code:");

        errorCodeTextField.setEditable(false);

        errorDescLabel.setLabelFor(errorDescPane);
        errorDescLabel.setText("<html>\nError<br>Description:\n</html>");
        errorDescLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        errorDescTextArea.setEditable(false);
        errorDescTextArea.setColumns(20);
        errorDescTextArea.setRows(5);
        errorDescPane.setViewportView(errorDescTextArea);

        javax.swing.GroupLayout authenticationPanelLayout = new javax.swing.GroupLayout(authenticationPanel);
        authenticationPanel.setLayout(authenticationPanelLayout);
        authenticationPanelLayout.setHorizontalGroup(
            authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(authenticationPanelLayout.createSequentialGroup()
                        .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userIdLabel)
                            .addComponent(tokenLabel)
                            .addComponent(apiKeyLabel))
                        .addGap(37, 37, 37)
                        .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tokenTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(userIdTextField)
                            .addComponent(apiKeyTextField)))
                    .addGroup(authenticationPanelLayout.createSequentialGroup()
                        .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(errorTypeTextField)
                            .addComponent(errorCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authenticationPanelLayout.createSequentialGroup()
                        .addComponent(errorDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorDescPane, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        authenticationPanelLayout.setVerticalGroup(
            authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tokenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tokenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apiKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apiKeyLabel))
                .addGap(39, 39, 39)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorDescPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Authentication", authenticationPanel);

        accountInfoButton.setText("Account Info");
        accountInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountInfoPanelLayout = new javax.swing.GroupLayout(accountInfoPanel);
        accountInfoPanel.setLayout(accountInfoPanelLayout);
        accountInfoPanelLayout.setHorizontalGroup(
            accountInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountInfoPanelLayout.createSequentialGroup()
                        .addComponent(accountInfoButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(accountInfoPropertySheet, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
                .addContainerGap())
        );
        accountInfoPanelLayout.setVerticalGroup(
            accountInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountInfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountInfoPropertySheet, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Account Info", accountInfoPanel);

        beanTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Choose>", "Folders", "Contexts", "Goals", "Locations" }));
        beanTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beanTypeComboBoxActionPerformed(evt);
            }
        });

        beanResultsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beanResultsComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout othersPanelLayout = new javax.swing.GroupLayout(othersPanel);
        othersPanel.setLayout(othersPanelLayout);
        othersPanelLayout.setHorizontalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, othersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(beanPropertySheet, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addGroup(othersPanelLayout.createSequentialGroup()
                        .addComponent(beanTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beanResultsComboBox, 0, 499, Short.MAX_VALUE)))
                .addContainerGap())
        );
        othersPanelLayout.setVerticalGroup(
            othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(othersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(othersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beanResultsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beanTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(beanPropertySheet, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Others", othersPanel);

        startDateLabel.setText("Start Date:");

        endDateLabel.setText("End Date:");

        completionLabel.setText("Completion Status:");

        taskIdLabel.setText("Task Id:");

        taskIdTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        rowStartLabel.setText("Row Start:");

        rowStartTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        numRowsLabel.setText("# Rows:");

        numRowsTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        clearSearchutton.setText("Clear Search");
        clearSearchutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSearchuttonActionPerformed(evt);
            }
        });

        searchButton.setText("Search !");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        tasksInResultLabel.setText("Tasks in Result:");

        tasksInResultTextField.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, taskQueryResult, org.jdesktop.beansbinding.ELProperty.create("${totalTaskCount}"), tasksInResultTextField, org.jdesktop.beansbinding.BeanProperty.create("text"), "totalTasks");
        bindingGroup.addBinding(binding);

        tasksInPageLabel.setText("Tasks in Page:");

        tasksInPageTextField.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, taskQueryResult, org.jdesktop.beansbinding.ELProperty.create("${queryTaskCount}"), tasksInPageTextField, org.jdesktop.beansbinding.BeanProperty.create("text"), "queryTasks");
        bindingGroup.addBinding(binding);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${tasks}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, taskQueryResult, eLProperty, tasksTable, "toodledoTasks");
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${childTaskCount}"));
        columnBinding.setColumnName("Child Task Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${parentTaskId}"));
        columnBinding.setColumnName("Parent Task Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${childTaskOrder}"));
        columnBinding.setColumnName("Child Task Order");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${title}"));
        columnBinding.setColumnName("Title");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${priority}"));
        columnBinding.setColumnName("Priority");
        columnBinding.setColumnClass(jtoodle.api.json.enums.Priority.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${status}"));
        columnBinding.setColumnName("Status");
        columnBinding.setColumnClass(jtoodle.api.json.enums.Status.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dueDate}"));
        columnBinding.setColumnName("Due Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${completedOn}"));
        columnBinding.setColumnName("Completed On");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${folderId}"));
        columnBinding.setColumnName("Folder Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${contextId}"));
        columnBinding.setColumnName("Context Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${goalId}"));
        columnBinding.setColumnName("Goal Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${locationId}"));
        columnBinding.setColumnName("Location Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${addedOn}"));
        columnBinding.setColumnName("Added On");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${modifiedOn}"));
        columnBinding.setColumnName("Modified On");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tasksScrollPane.setViewportView(tasksTable);

        javax.swing.GroupLayout tasksPanelLayout = new javax.swing.GroupLayout(tasksPanel);
        tasksPanel.setLayout(tasksPanelLayout);
        tasksPanelLayout.setHorizontalGroup(
            tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchResultsSeparator)
                    .addComponent(tasksScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addGroup(tasksPanelLayout.createSequentialGroup()
                        .addComponent(tasksInResultLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tasksInResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tasksInPageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tasksInPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tasksPanelLayout.createSequentialGroup()
                        .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tasksPanelLayout.createSequentialGroup()
                                .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(endDateLabel)
                                    .addComponent(completionLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(tasksPanelLayout.createSequentialGroup()
                                .addComponent(startDateLabel)
                                .addGap(64, 64, 64)))
                        .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(startDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(endDatePicker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(completionComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rowStartLabel)
                            .addComponent(numRowsLabel)
                            .addComponent(taskIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(taskIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(rowStartTextField)
                            .addComponent(numRowsTextField))
                        .addGap(18, 18, 18)
                        .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(clearSearchutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        tasksPanelLayout.setVerticalGroup(
            tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(startDateLabel)
                    .addComponent(startDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taskIdLabel)
                    .addComponent(taskIdTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateLabel)
                    .addComponent(rowStartLabel)
                    .addComponent(rowStartTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearSearchutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(completionLabel)
                    .addComponent(numRowsLabel)
                    .addComponent(numRowsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchResultsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tasksInResultLabel)
                    .addComponent(tasksInResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tasksInPageLabel)
                    .addComponent(tasksInPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tasksScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Tasks", tasksPanel);

        fileMenu.setText("File");

        loginMenuItem.setText("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loginMenuItem);

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(logoutMenuItem);
        fileMenu.add(exitSeparator);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void accountInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountInfoButtonActionPerformed
		try {
			AccountInfo bean = new GetAccountInfo().requestBean();
			accountInfoPropertySheet.setNodes( new Node[] { new BeanNode( bean ) } );
		} catch( IntrospectionException | IOException | JToodleException ex ) {
			logger.log( Level.SEVERE, null, ex );
			try {
				accountInfoPropertySheet.setNodes( new Node[] { new BeanNode( ex ) } );
			} catch( IntrospectionException ex1 ) {
				logger.log( Level.SEVERE, null, ex1 );
			}

			if( handledInvalidKey( ex ) ) {
				accountInfoButtonActionPerformed( null );
			}
		}
    }//GEN-LAST:event_accountInfoButtonActionPerformed

    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
		JXLoginPane.Status status = JXLoginPane.showLoginDialog( this, new LoginService() {
			@Override
			public boolean authenticate( String name, char[] password, String server ) {
				errorCodeTextField.setText( null );
				errorDescTextArea.setText( null );

				try {
					AuthCache.login( name, new String( password ) );

					userIdTextField.setText( AuthCache.getUserId() );
					tokenTextField.setText( AuthCache.getToken() );
					apiKeyTextField.setText( AuthCache.getApiKey() );

					return( true );
				} catch( JToodleException jte ) {
					errorTypeTextField.setText( jte.getClass().getName() );
					errorCodeTextField.setText( "" + jte.getErrorCode() );
					errorDescTextArea.setText( jte.getMessage() );

					logger.log( Level.SEVERE, null, jte );
					return( false );
				} catch( Exception ex ) {
					errorTypeTextField.setText( ex.getClass().getName() );
					errorCodeTextField.setText( "N/A" );
					errorDescTextArea.setText( ex.getMessage() );

					logger.log( Level.SEVERE, null, ex );
					return( false );
				}
			}
		} );
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        int yn = JOptionPane.showConfirmDialog( this, "Are you sure you want to logout ?" );

		if( yn == JOptionPane.OK_OPTION ) {
			AuthCache.logout();
		}
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void beanResultsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beanResultsComboBoxActionPerformed
		try {
			if( beanResultsComboBox.getSelectedItem() == null ) {
				beanPropertySheet.setNodes( new Node[] {} );
			} else {
				beanPropertySheet.setNodes( new Node[] {
					new BeanNode( beanResultsComboBox.getSelectedItem() )
				});
			}
		} catch( IntrospectionException ex ) {
			logger.log( Level.SEVERE, null, ex );
		}
    }//GEN-LAST:event_beanResultsComboBoxActionPerformed

    private void beanTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beanTypeComboBoxActionPerformed
		beanResultsComboBox.removeAllItems();
		beanPropertySheet.setNodes( new Node[] {} );

		try {
			List beanList = null;

			switch( beanTypeComboBox.getSelectedItem().toString() ) {
				case "Folders": {
					beanList = new GetFolders().requestBeanList();
					break;
				}
				case "Contexts": {
					JOptionPane.showMessageDialog(
						this.getRootPane(),
						"This function is not yet available"
					);
					break;
				}
				case "Goals": {
					JOptionPane.showMessageDialog(
						this.getRootPane(),
						"This function is not yet available"
					);
					break;
				}
				case "Locations": {
					JOptionPane.showMessageDialog(
						this.getRootPane(),
						"This function is not yet available"
					);
					break;
				}
				default: {
					break;
				}
			}

			if( !NullSafe.isNullOrEmpty( beanList ) ) {
				for( Object o: beanList ) {
					beanResultsComboBox.addItem( o );
				}
			} else {
				beanResultsComboBox.addItem(
					"<no results for: " + beanTypeComboBox.getSelectedItem() + ">" );
			}

			beanResultsComboBoxActionPerformed( null );

		} catch( IOException | JToodleException ex ) {
			logger.log( Level.SEVERE, null, ex );
			try {
				beanResultsComboBox.addItem( ex );
				beanPropertySheet.setNodes( new Node[] { new BeanNode( ex ) } );
			} catch( IntrospectionException ex1 ) {
				logger.log( Level.SEVERE, null, ex1 );
			}

			if( handledInvalidKey( ex ) ) {
				beanTypeComboBoxActionPerformed( null );
			}
		}
    }//GEN-LAST:event_beanTypeComboBoxActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
		try {
			GetTasks request = new GetTasks();

			request.setStartDate( startDatePicker.getDate() );
			request.setEndDate( endDatePicker.getDate() );
			request.setCompletionCriteria( (GetTasks.CompletionCriteria) completionComboBox.getSelectedItem() );
			if( ! NullSafe.isNullOrEmpty( taskIdTextField.getText() ) ) {
				request.setTaskId( Integer.parseInt( taskIdTextField.getText() ) );
			}
			if( ! NullSafe.isNullOrEmpty( rowStartTextField.getText() ) ) {
				request.setPaginationRowStart( Integer.parseInt( rowStartTextField.getText() ) );
			}
			if( ! NullSafe.isNullOrEmpty( numRowsTextField.getText() ) ) {
				request.setPaginationNumTasks( Integer.parseInt( numRowsTextField.getText() ) );
			}

			JTableUtil.configureTable( tasksTable, null );

			TaskQueryResult result = request.requestBean();
			taskQueryResult.updateProperties( result );

			JTableUtil.resizeTableColumnsToFit( tasksTable );

			logger.log( Level.INFO, "TaskQueryResult.totalTaskCount={0}", result.getTotalTaskCount() );
			logger.log( Level.INFO, "TaskQueryResult.queryTaskCount={0}", result.getQueryTaskCount() );
			logger.log( Level.INFO, "TaskQueryResult.tasks.size={0}", result.getTasks().size() );
		} catch( IOException | JToodleException ex ) {
			logger.log( Level.SEVERE, null, ex );

			if( handledInvalidKey( ex ) ) {
				searchButtonActionPerformed( null );
			}
		}
    }//GEN-LAST:event_searchButtonActionPerformed

    private void clearSearchuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSearchuttonActionPerformed
		this.startDatePicker.setDate( null );
		this.endDatePicker.setDate( null );
		this.completionComboBox.setSelectedItem( GetTasks.CompletionCriteria.All_Tasks );
		this.taskIdTextField.setText( null );
		this.rowStartTextField.setText( null );
		this.numRowsTextField.setText( null );
		((ListBindingManager)this.tasksTable.getModel()).setElements( new ArrayList(), true );
    }//GEN-LAST:event_clearSearchuttonActionPerformed

	private boolean handledInvalidKey( Exception ex ) {
		boolean val = false;

		if( ex instanceof JToodleException ) {
			JToodleException jte = (JToodleException) ex;

			if( jte.getErrorCode() == 2 ) {
				// Error Code 2 = Invalid Key
				AuthCache.logout();
				loginMenuItemActionPerformed( null );
				val = true;
			}
		}

		return( val );
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
		try {
			/* Create and display the form */
			java.awt.EventQueue.invokeAndWait( new Runnable() {
				@Override
				public void run() {
					new MainTestForm().setVisible(true);
				}
			});
		} catch( InterruptedException | InvocationTargetException ex ) {
			logger.log( Level.SEVERE, null, ex );
		}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountInfoButton;
    private javax.swing.JPanel accountInfoPanel;
    private org.openide.explorer.propertysheet.PropertySheet accountInfoPropertySheet;
    private javax.swing.JLabel apiKeyLabel;
    private javax.swing.JTextField apiKeyTextField;
    private javax.swing.JPanel authenticationPanel;
    private org.openide.explorer.propertysheet.PropertySheet beanPropertySheet;
    private javax.swing.JComboBox beanResultsComboBox;
    private javax.swing.JComboBox beanTypeComboBox;
    private javax.swing.JButton clearSearchutton;
    private javax.swing.JComboBox completionComboBox;
    private javax.swing.JLabel completionLabel;
    private javax.swing.JLabel endDateLabel;
    private org.jdesktop.swingx.JXDatePicker endDatePicker;
    private javax.swing.JLabel errorCodeLabel;
    private javax.swing.JTextField errorCodeTextField;
    private javax.swing.JLabel errorDescLabel;
    private javax.swing.JScrollPane errorDescPane;
    private javax.swing.JTextArea errorDescTextArea;
    private javax.swing.JLabel errorTypeLabel;
    private javax.swing.JTextField errorTypeTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JPopupMenu.Separator exitSeparator;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel numRowsLabel;
    private javax.swing.JFormattedTextField numRowsTextField;
    private javax.swing.JPanel othersPanel;
    private javax.swing.JLabel rowStartLabel;
    private javax.swing.JFormattedTextField rowStartTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JSeparator searchResultsSeparator;
    private javax.swing.JLabel startDateLabel;
    private org.jdesktop.swingx.JXDatePicker startDatePicker;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel taskIdLabel;
    private javax.swing.JFormattedTextField taskIdTextField;
    private jtoodle.api.test.BindableTaskQueryResult taskQueryResult;
    private javax.swing.JLabel tasksInPageLabel;
    private javax.swing.JTextField tasksInPageTextField;
    private javax.swing.JLabel tasksInResultLabel;
    private javax.swing.JTextField tasksInResultTextField;
    private javax.swing.JPanel tasksPanel;
    private javax.swing.JScrollPane tasksScrollPane;
    private javax.swing.JTable tasksTable;
    private javax.swing.JLabel tokenLabel;
    private javax.swing.JTextField tokenTextField;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JTextField userIdTextField;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
