/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jtoodle.api.test.web;

import java.beans.IntrospectionException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jtoodle.api.auth.AuthCache;
import jtoodle.api.auth.AuthExceptionHandler;
import jtoodle.api.bean.core.AccountInfo;
import jtoodle.api.bean.util.JToodleException;
import jtoodle.api.request.web.AccountInfoOperations;
import org.openide.nodes.BeanNode;
import org.openide.nodes.Node;

/**
 *
 * @author Justo_Casablanca
 */
public class AccountInfoPanel extends javax.swing.JPanel {

	private static final Logger logger = Logger.getLogger( AccountInfoPanel.class.getName() );

	/** Creates new form AccountInfoPanel */
	public AccountInfoPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountInfoButton = new javax.swing.JButton();
        accountInfoPropertySheet = new org.openide.explorer.propertysheet.PropertySheet();

        org.openide.awt.Mnemonics.setLocalizedText(accountInfoButton, org.openide.util.NbBundle.getMessage(AccountInfoPanel.class, "AccountInfoPanel.accountInfoButton.text")); // NOI18N
        accountInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accountInfoButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(accountInfoPropertySheet, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountInfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountInfoPropertySheet, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountInfoButtonActionPerformed
        try {
            AccountInfoOperations aiOps = new AccountInfoOperations();
            AccountInfo bean = aiOps.searchSingle();
            accountInfoPropertySheet.setNodes( new Node[] { new BeanNode( bean ) } );
        } catch( IntrospectionException | IOException | JToodleException ex ) {
            logger.log( Level.SEVERE, null, ex );
            try {
                accountInfoPropertySheet.setNodes( new Node[] { new BeanNode( ex ) } );
            } catch( IntrospectionException ex1 ) {
                logger.log( Level.SEVERE, null, ex1 );
            }

            if( AuthExceptionHandler.handledInvalidKey( this, ex ) ) {
                accountInfoButtonActionPerformed( null );
            }
        }
    }//GEN-LAST:event_accountInfoButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountInfoButton;
    private org.openide.explorer.propertysheet.PropertySheet accountInfoPropertySheet;
    // End of variables declaration//GEN-END:variables
}
