/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jtoodle.api.test.web;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jtoodle.api.auth.AuthCache;
import jtoodle.api.bean.util.JToodleException;
import org.jdesktop.swingx.JXLoginPane;
import org.jdesktop.swingx.auth.LoginService;

/**
 *
 * @author Justo_Casablanca
 */
public class AuthenticationPanel extends javax.swing.JPanel {

	private static final Logger logger = Logger.getLogger( AuthenticationPanel.class.getName() );

	/** Creates new form AuthenticationPanel */
	public AuthenticationPanel() {
		super();
		initComponents();
		initComponents2();
	}

	public void login() {
		JXLoginPane.showLoginDialog( this, new LoginService() {
			@Override
			public boolean authenticate( String name, char[] password, String server ) {
				clearAuthTextFields();

				try {
					AuthCache.login( name, new String( password ) );

					return( true );
				} catch( JToodleException jte ) {
					setAuthTextFields( jte );

					logger.log( Level.SEVERE, null, jte );
					return( false );
				} catch( Exception ex ) {
					setAuthTextFields( ex );

					logger.log( Level.SEVERE, null, ex );
					return( false );
				} finally {
					setAuthTextFields();
				}
			}
		} );
	}

	public void logout() {
        int yn = JOptionPane.showConfirmDialog( this, "Are you sure you want to logout ?" );

		if( yn == JOptionPane.OK_OPTION ) {
			AuthCache.logout();
			setAuthTextFields();
		}
	}

	private void initComponents2() {
		setAuthTextFields();
		if( ! AuthCache.isAuthenticated() ) {
			login();
		}
	}

	private void clearAuthTextFields() {
		userIdTextField.setText( null );
		tokenTextField.setText( null );
		apiKeyTextField.setText( null );
	}

	private void setAuthTextFields() {
		if( AuthCache.isAuthenticated() ) {
			try {
				userIdTextField.setText( AuthCache.getUserId() );
				tokenTextField.setText( AuthCache.getToken() );
				apiKeyTextField.setText( AuthCache.getApiKey() );
			} catch( JToodleException ex ) {
				logger.log( Level.SEVERE,
							"MainTestForm.setAuthTextFields()",
							ex );
			}
		} else {
			clearAuthTextFields();
		}
	}

	private void setAuthTextFields( JToodleException jte ) {
		errorTypeTextField.setText( jte.getClass().getName() );
		errorCodeTextField.setText( "" + jte.getErrorCode() );
		errorDescTextArea.setText( jte.getMessage() );
	}

	private void setAuthTextFields( Exception ex ) {
		errorTypeTextField.setText( ex.getClass().getName() );
		errorCodeTextField.setText( "N/A" );
		errorDescTextArea.setText( ex.getMessage() );
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userIdLabel = new javax.swing.JLabel();
        userIdTextField = new javax.swing.JTextField();
        tokenLabel = new javax.swing.JLabel();
        tokenTextField = new javax.swing.JTextField();
        apiKeyLabel = new javax.swing.JLabel();
        apiKeyTextField = new javax.swing.JTextField();
        errorTypeLabel = new javax.swing.JLabel();
        errorTypeTextField = new javax.swing.JTextField();
        errorCodeLabel = new javax.swing.JLabel();
        errorCodeTextField = new javax.swing.JTextField();
        errorDescLabel = new javax.swing.JLabel();
        errorDescPane = new javax.swing.JScrollPane();
        errorDescTextArea = new javax.swing.JTextArea();

        org.openide.awt.Mnemonics.setLocalizedText(userIdLabel, org.openide.util.NbBundle.getMessage(AuthenticationPanel.class, "AuthenticationPanel.userIdLabel.text")); // NOI18N

        userIdTextField.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(tokenLabel, org.openide.util.NbBundle.getMessage(AuthenticationPanel.class, "AuthenticationPanel.tokenLabel.text")); // NOI18N

        tokenTextField.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(apiKeyLabel, org.openide.util.NbBundle.getMessage(AuthenticationPanel.class, "AuthenticationPanel.apiKeyLabel.text")); // NOI18N

        apiKeyTextField.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(errorTypeLabel, org.openide.util.NbBundle.getMessage(AuthenticationPanel.class, "AuthenticationPanel.errorTypeLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(errorCodeLabel, org.openide.util.NbBundle.getMessage(AuthenticationPanel.class, "AuthenticationPanel.errorCodeLabel.text")); // NOI18N

        errorCodeTextField.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(errorDescLabel, org.openide.util.NbBundle.getMessage(AuthenticationPanel.class, "AuthenticationPanel.errorDescLabel.text")); // NOI18N
        errorDescLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        errorDescTextArea.setEditable(false);
        errorDescTextArea.setColumns(20);
        errorDescTextArea.setRows(5);
        errorDescPane.setViewportView(errorDescTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(apiKeyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(tokenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tokenTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(apiKeyTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userIdTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(errorTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errorCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(errorDescLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorDescPane)
                            .addComponent(errorCodeTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(errorTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tokenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tokenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apiKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apiKeyLabel))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(errorDescPane))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apiKeyLabel;
    private javax.swing.JTextField apiKeyTextField;
    private javax.swing.JLabel errorCodeLabel;
    private javax.swing.JTextField errorCodeTextField;
    private javax.swing.JLabel errorDescLabel;
    private javax.swing.JScrollPane errorDescPane;
    private javax.swing.JTextArea errorDescTextArea;
    private javax.swing.JLabel errorTypeLabel;
    private javax.swing.JTextField errorTypeTextField;
    private javax.swing.JLabel tokenLabel;
    private javax.swing.JTextField tokenTextField;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JTextField userIdTextField;
    // End of variables declaration//GEN-END:variables
}
